import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Header from "~/components/Header";
import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import Pusher from "pusher-js";
import { env } from "~/env.mjs";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mx-auto max-w-screen-md">
        <div className="my-5 text-center">
          <h1 className="text-5xl">Ask-Em</h1>
          <p className="text-2xl">Ask people questions</p>
        </div>
        {session && (
          <SignedIn
            username={session.user.name ?? "User"}
            uid={session.user.id}
          />
        )}
        <Link href={"/user/clhfjgcnl0000gjhjolrhsepx"}>Nom House</Link>
      </main>
    </>
  );
};

export default Home;

const SignedIn = ({ username, uid }: { username: string; uid: string }) => {
  const { data: unansweredLength } =
    api.question.getAllUnansweredLength.useQuery();
  const [length, setLength] = useState<number | undefined>();

  useEffect(() => {
    setLength(unansweredLength);
  }, [unansweredLength]);

  useEffect(() => {
    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;

    const pusher = new Pusher(env.NEXT_PUBLIC_PUSHER_KEY, {
      cluster: env.NEXT_PUBLIC_PUSHER_CLUSTER,
    });

    const channel = pusher.subscribe(`user-${uid}`);
    channel.bind("new-question", () => {
      setLength((prev) => (prev ? (prev += 1) : prev));
    });

    return () => {
      pusher.disconnect();
    };
  }, [uid]);

  return (
    <div>
      <h2>Welcome {username}</h2>
      <p>
        You have {length} question{length === 1 ? "" : "s"} waiting for you!
      </p>
      <Link href={`/answer/${uid}`} className="cursor-pointer">
        Answer Some Questions!
      </Link>
      <Link href={`/user/${uid}`} className="cursor-pointer">
        View Your Answers
      </Link>
    </div>
  );
};
